<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZs5nmlp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZs5nmlp/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZs5nmlp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZs5nmlp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZs5nmlp\appProdProjectContainer([
    'container.build_hash' => 'Zs5nmlp',
    'container.build_id' => '62e00f1c',
    'container.build_time' => 1633003046,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZs5nmlp');
